# Basic settings
from_latest_tag = false
ignore_merge_commits = true
skip_untracked = true
tag_prefix = "test/v"

[commit_types]
feat = { changelog_title = "Features" }
fix = { changelog_title = "Bug Fixes" }
build = { changelog_title = "Build Updates" }
perf = { changelog_title = "Performance Improvements" }

chore = { omit_from_changelog = true }
ci = { omit_from_changelog = true }
docs = { omit_from_changelog = true }
refactor = { omit_from_changelog = true }
style = { omit_from_changelog = true }
test = { omit_from_changelog = true }

# Changelog settings
[changelog]
path = "CHANGELOG.md"
template = "simple"
remote = "github.com"
owner = "RangerRick"
repository = "cocogitto-test"
